[tool.ruff]
extend = "../pyproject.toml"

[tool.ruff.lint]
ignore = [
    "S105", "S106", # allow hardcoded passwords
    "T201", # allow print()
    "ERA001", # allow commented-out code
    "PLR2004", # allow magic values in comparisons
    "ASYNC230", # allow blocking calls in async functions for demonstration purposes
]
