"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import flix.lib.proto.transfer_pb2
import grpc

class FileTransferStub:
    """FileTransfer is the server which handles data transfers."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    Transfer: grpc.StreamStreamMultiCallable[
        flix.lib.proto.transfer_pb2.TransferReq,
        flix.lib.proto.transfer_pb2.TransferResp,
    ]
    """Transfer is the primary endpoint for the service."""

class FileTransferServicer(metaclass=abc.ABCMeta):
    """FileTransfer is the server which handles data transfers."""

    @abc.abstractmethod
    def Transfer(
        self,
        request_iterator: collections.abc.Iterator[flix.lib.proto.transfer_pb2.TransferReq],
        context: grpc.ServicerContext,
    ) -> collections.abc.Iterator[flix.lib.proto.transfer_pb2.TransferResp]:
        """Transfer is the primary endpoint for the service."""

def add_FileTransferServicer_to_server(servicer: FileTransferServicer, server: grpc.Server) -> None: ...
