name: PR Checker

on:
  pull_request:

defaults:
  run:
    working-directory: ./flixpy

jobs:
  ruff-check:
    name: Ruff Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/setup
        with:
          python_version: ${{ matrix.python_version }}
      - name: Test
        run: poetry run ruff check
  ruff-format:
    name: Ruff Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/setup
        with:
          python_version: ${{ matrix.python_version }}
      - name: Test
        run: poetry run ruff format --check
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/workflows/setup
        with:
          python_version: ${{ matrix.python_version }}
      - name: Test
        run: poetry run mypy
